package com.example.imindevicelibrary.bean;

import java.util.List;

public class ControlBean {
    public String name;
    public String version;
    public List<ApplicationPolicy> applications;
    public Long maximumTimeToLock;
    public Boolean screenCaptureDisabled;
    public Boolean cameraDisabled;
    public String keyguardDisabledFeatures;
    public String defaultPermissionPolicy;
    public List<PersistentPreferredActivity> persistentPreferredActivities;
    public Object openNetworkConfiguration;
//    public SystemUpdate systemUpdate;
    public List<String> accountTypesWithManagementDisabled;
    public Boolean addUserDisabled;
    public Boolean adjustVolumeDisabled;
    public Boolean factoryResetDisabled;
    public Boolean installAppsDisabled;
    public Boolean mountPhysicalMediaDisabled;
    public Boolean modifyAccountsDisabled;
    public Boolean safeBootDisabled;
    public Boolean uninstallAppsDisabled;
    public Boolean statusBarDisabled;
    public Boolean keyguardDisabled;
    public Boolean privateKeySelectionEnabled;
    public Integer minimumApiLevel;
    public StatusReportingSettings statusReportingSettings;
    public Boolean bluetoothContactSharingDisabled;
    public String shortSupportMessage;
    public String longSupportMessage;
    public String[] choosePrivateKeyRules;
    public PasswordRequirements passwordRequirements;
    public Boolean wifiConfigsLockdownEnabled;
    public Boolean bluetoothConfigDisabled;
    public Boolean cellBroadcastsConfigDisabled;
    public Boolean credentialsConfigDisabled;
    public Boolean mobileNetworksConfigDisabled;
    public Boolean tetheringConfigDisabled;
    public Boolean vpnConfigDisabled;
    public Boolean wifiConfigDisabled;
    public Boolean createWindowsDisabled;
    public Boolean networkResetDisabled;
    public Boolean outgoingBeamDisabled;
    public Boolean outgoingCallsDisabled;
    public Boolean removeUserDisabled;
    public Boolean shareLocationDisabled;
    public Boolean smsDisabled;
    public Boolean unmuteMicrophoneDisabled;
    public Boolean usbFileTransferDisabled;
    public Boolean ensureVerifyAppsEnabled;
    public String[] permittedInputMethods;
    public String stayOnPluggedModes;
    public ProxyInfo recommendedGlobalProxy;
    public Boolean setUserIconDisabled;
    public Boolean setWallpaperDisabled;
//    public List<ChoosepublicKeyRule> choosepublicKeyRules;
    public AlwaysOnVpnPackage alwaysOnVpnPackage;
    public String[] frpAdminEmails;
    public String deviceOwnerLockScreenInfo;
    public Boolean dataRoamingDisabled;
//    public LocationMode locationMode;
    public Boolean networkEscapeHatchEnabled;
    public Boolean bluetoothDisabled;
//    public List<ComplianceRule> complianceRules;
    public Boolean blockApplicationsEnabled;
    public Boolean installUnknownSourcesAllowed;
    public Boolean debuggingFeaturesAllowed;
    public Boolean funDisabled;
    public Boolean autoTimeRequired;
    public List<PersistentPreferredActivity> permittedAccessibilityServices;
//    public AppAutoUpdatePolicy appAutoUpdatePolicy;
    public Boolean kioskCustomLauncherEnabled;
//    public List<AppTrack> androidDevicePolicyTracks;
    public Boolean skipFirstUseHintsEnabled;
    public Boolean publicKeySelectionEnabled;
    public Boolean encryptionPolicy;
    public Boolean usbMassStorageEnabled;
    public List<PermissionGrant> permissionGrants;
//    public PlayStoreMode playStoreMode;
    public String[] setupActions;
//    public List<PasswordRequirements> passwordPolicies;
//    public List<PolicyEnforcementRule> policyEnforcementRules;
    public KioskCustomization kioskCustomization;
    public AdvancedSecurityOverrides advancedSecurityOverrides;
    public PersonalUsagePolicies personalUsagePolicies;
    public String autoDateAndTimeZone;
//    public List<OncCertificateProvider> oncCertificateProviders;
//    public CrossProfilePolicies crossProfilePolicies;
    public String preferentialNetworkService;
//    public UsageLog usageLog;
//    public CameraAccess cameraAccess;
//    public MicrophoneAccess microphoneAccess;
    public DeviceConnectivityManagement deviceConnectivityManagement;
    public DeviceRadioState deviceRadioState;
//    public CredentialProviderPolicyDefault credentialProviderPolicyDefault;
    public String printingPolicy;
    public DisplaySettings displaySettings;
    public GooglePlayController googlePlayController;
}
